name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        node-version: [18.x]

    runs-on: ${{ matrix.platform }}
    name: "${{ matrix.platform }} ${{ matrix.node-version }}"

    env:
      ADDRESS_ALICE: "0x70997970C51812dc3A010C7d01b50e0d17dc79C8"
      ADDRESS_BOB: "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC"
      PRIVATE_KEY_BOB: "0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a"
      ADDRESS_MALLORY: "0x90F79bf6EB2c4f870365E785982E1f101E93b906"
      PRIVATE_KEY_MALLORY: "0x7c852118294e51e653712a81e05800f419141751be58f605c371e15141b007a6"
      PRIMODIUM_RPC_URL: "https://primodium-sepolia.rpc.caldera.xyz/http"
      WORLD_ADDRESS: "0x46c1e9dd144fcf5477a542d3152d28bc0cfba0b6"
      BLOCK_NUMBER: "5701830"

    steps:
      - uses: actions/checkout@v4

      - name: Setup foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Run ci for contracts
        run: cd packages/contracts && pnpm run ci
